const ADD_RECIPE = 'ADD_RECIPE';
const FETCH_BEGIN = 'FETCH_RECIPE_BEGIN';
const FETCH_ERROR = 'FETCH_RECIPE_ERROR';
const FETCH_SUCCESS = 'FETCH_RECIPE_SUCCESS';
const DELETE_RECIPE = 'DELETE_RECIPE';


export default {
  FETCH_BEGIN,
  FETCH_SUCCESS,
  FETCH_ERROR,
  ADD_RECIPE,
  DELETE_RECIPE,
};
